### ISSUE TITLE
One error after another

### ISSUE THREAD

**Issue by selfagency** [Strider-CD/strider-gitlab#116]
Sadly, I keep running into one error after another trying to get this app up and running.

If I click on the wrench next to a project, or on `deploy`, or on a test result, I get a 504 error.

If I click on a repo's name I get:

```
Connect
500 Error: Failed to lookup view "dist/index.html" in views directories "/var/www/selfagency-ci/live/dist-lib/views" or "/var/www/selfagency-ci/live/client-ember"
   at Function.render (/var/www/selfagency-ci/live/node_modules/express/lib/application.js:580:17)
   at ServerResponse.render (/var/www/selfagency-ci/live/node_modules/express/lib/response.js:1012:7)
   at /var/www/selfagency-ci/live/dist-lib/routes/index.js:61:17
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:2955:19
   at wrapper (/var/www/selfagency-ci/live/node_modules/async/dist/async.js:268:20)
   at iterateeCallback (/var/www/selfagency-ci/live/node_modules/async/dist/async.js:421:28)
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:321:20
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:2953:17
   at /var/www/selfagency-ci/live/dist-lib/jobs.js:109:9
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:2955:19
   at wrapper (/var/www/selfagency-ci/live/node_modules/async/dist/async.js:268:20)
   at iteratorCallback (/var/www/selfagency-ci/live/node_modules/async/dist/async.js:495:17)
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:321:20
   at /var/www/selfagency-ci/live/node_modules/async/dist/async.js:2953:17
   at /var/www/selfagency-ci/live/dist-lib/jobs.js:84:20
   at /var/www/selfagency-ci/live/node_modules/mongoose/lib/model.js:4886:16
   at /var/www/selfagency-ci/live/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
   at /var/www/selfagency-ci/live/node_modules/mongoose/lib/model.js:4909:21
   at /var/www/selfagency-ci/live/node_modules/mongoose/lib/query.js:4378:11
   at /var/www/selfagency-ci/live/node_modules/kareem/index.js:135:16
   at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by knownasilya** [comment]
That was fixed in the latest release, did you get a chance to update?

**Comment by knownasilya** [comment]
If you still see an issue, please file under the strider repo.
