### ISSUE TITLE
Strider throws when invoked for invalid project

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider-gitlab#90]
- The git URL for a project changed.
- Strider is activated via webhook to start a new build.
- Strider can't find the code.

```
2017-03-20T09:19:57.713Z - ESC[31merrorESC[39m: TypeError: Cannot read property 'author' of undefined
    at pushJob (/data/strider/strider-gitlab/lib/webhooks.js:75:19)
    at startFromCommit (/data/strider/strider-gitlab/lib/webhooks.js:35:16)
    at receiveWebhook (/data/strider/strider-gitlab/lib/webhooks.js:102:16)
    at Layer.handle [as handle_request] (/data/strider/strider/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/strider/strider/node_modules/express/lib/router/route.js:131:13)
    at projectProvider (/data/strider/strider/lib/middleware.js:118:3)
    at Layer.handle [as handle_request] (/data/strider/strider/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/strider/strider/node_modules/express/lib/router/route.js:131:13)
    at /data/strider/strider/lib/middleware.js:234:7
    at /data/strider/strider/node_modules/mongoose/lib/query.js:2555:18
    at tryCatcher (/data/strider/strider/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/strider/strider/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/data/strider/strider/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/data/strider/strider/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/data/strider/strider/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/data/strider/strider/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/data/strider/strider/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/data/strider/strider/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by oliversalzburg** [comment]
I think my error description and the stack trace are 2 separate issues :P

**Comment by knownasilya** [comment]
Closing since a guard was added by you. Not sure what the title is about exactly.
